### PR TITLE
Update Amazon Workspaces to 4.6.0.4187

### PR DESCRIPTION
**Pull request by bbhtt**
- Update hiredis to 0.14.1. Dependency as per control file
 - Add icu63 to resolve `Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support`
 - Add graphicsmagick. Dependency as per control file
 - Change deb branch to focal

A bit late since I didn't realise there was a different deb dist.

### CODE REVIEW

**Comment by bbhtt** [comment]
@compuguy Can you please test this build too? It doesn't solve the issue you wanted, but it's an upgrade from the current 4.5 version to 4.6 version and I want to make sure it's working.

Thanks!

**Comment by compuguy** [comment]
@bbhtt Just tried it on my RHEL 8 box. Works fine with older runtime,

**Comment by bbhtt** [comment]
> @bbhtt Just tried it on my RHEL 8 box. Works fine with the older runtime,

Awesome I'll merge. Update will be published in 4-5 hours.

**Comment by compuguy** [comment]
> > @bbhtt Just tried it on my RHEL 8 box. Works fine with the older runtime,
> 
> Awesome I'll merge. Update will be published in 4-5 hours.

Excellent Glad I could help!

**Pull request merged**
